Full IOMMU / VFIO support to ixy
emmericp/ixy pull request #14
Opened 2019-01-31 15:30 UTC by huberste

This pull request adds full IOMMU / VFIO support to ixy. It will compile without additional cmake flags and decide at runtime whether to use VFIO or not (by checking if the IOMMU is enabled and the VFIO driver is loaded for the device).
All initialized ixy devices (i.e. NICs) will be in the same VFIO container, thus be able to read from each others memory (needed for the forwarder).

2019-02-21 22:11 UTC, emmericp requested changes

2019-02-21 22:11 UTC, emmericp commented on src/pci.c
> +int fileexists(const char* filename){
used exactly once, better to inline for now

2019-02-21 22:11 UTC, emmericp commented on src/libixy-vfio.c
> +		if(ret != 0){
whitespace

2019-02-21 22:11 UTC, emmericp commented on src/libixy-vfio.c
> +	if(ret == -1){
whitespace

2019-02-21 22:11 UTC, emmericp commented on src/libixy-vfio.c
> +	if(vfio_fd < 0){
whitespace

2019-02-21 22:11 UTC, emmericp commented on src/libixy-vfio.c
> +	if(ret == -1){
whitespace

2019-02-21 22:11 UTC, emmericp commented on src/memory.c
> +/* reads the global VFIO container */
prefer C++-style comments

2019-02-21 22:11 UTC, emmericp commented on src/memory.c
> +/* globally sets the VFIO container and returns the set value */
C++-style comments, please

2019-02-21 22:11 UTC, emmericp commented on src/memory.h
> +/* reads the global VFIO container */
C++-style comments

2019-02-21 22:11 UTC, emmericp commented on src/memory.h
> +/* globally sets the VFIO container */
C++-style comments

2019-02-21 22:11 UTC, emmericp commented on src/libixy-vfio.c
> +/* returns the devices file descriptor or -1 on error */
C++-style comments

2019-02-21 22:11 UTC, emmericp commented on src/libixy-vfio.c
> +/* returns iova (physical address of the DMA memory from device view) on success */
C++-style comments

2019-02-21 22:11 UTC, emmericp commented on src/libixy-vfio.c
> +/* unmaps previously mapped DMA region. returns 0 on success */
C++-style comments

2019-02-21 22:11 UTC, emmericp commented on src/libixy-vfio.h
> +
C++-style comments in the whole file unless multiple lines are needed for a function description

2019-02-28 10:39 UTC, emmericp requested changes

2019-02-28 10:39 UTC, emmericp commented on src/driver/ixgbe.c
> +	dev->ixy.vfio = stat(path,&buffer) == 0;
space missing

2019-02-28 10:39 UTC, emmericp commented on src/libixy-vfio.c
> +				 conf_reg.offset + command_register_offset) == 2);
merge into a single line, please

2019-02-28 10:39 UTC, emmericp commented on src/libixy-vfio.c
> +				  conf_reg.offset + command_register_offset) == 2);
merge into a single line, please

2019-02-28 10:39 UTC, emmericp commented on src/libixy-vfio.c
> +		cfd = open("/dev/vfio/vfio", O_RDWR);
is this world-writable by default or do we need an additional chown in the setup instructions?

2019-02-28 10:39 UTC, emmericp commented on src/libixy-vfio.c
> +								"mmap vfio bar0 resource");
this formatting looks wrong with both tab size 4 and 8; I'd probably just merge it into one line?

2019-02-28 10:39 UTC, emmericp commented on src/libixy-vfio.c
> +		(uint64_t) vaddr; // Identity mapping makes sense here because why not
single line

2019-02-28 10:39 UTC, emmericp commented on src/libixy-vfio.c
> +		(uint64_t) vaddr; // Identity mapping makes sense here because why not
should this be called identity mapping? it maps the iova to the normal virtual address? wouldn't identity mapping be iova == physical address?

maybe change comment to "map iova to our virtual address"?

2019-02-28 10:39 UTC, emmericp commented on src/libixy-vfio.c
> +		.size = size};
closing brace on new line

2019-02-28 10:39 UTC, emmericp commented on src/memory.c
> +			.phy = iova};
closing brace to next line

2019-02-28 10:39 UTC, emmericp commented on src/memory.c
> +	mem = memory_allocate_dma(num_entries * entry_size, false);
undo this change please

2019-02-28 10:39 UTC, emmericp commented on src/memory.c
> +int get_vfio_container() { return VFIO_CONTAINER_FILE_DESCRIPTOR; }
newlines, please

2019-02-28 10:39 UTC, emmericp commented on src/memory.c
> +void set_vfio_container(int fd) { VFIO_CONTAINER_FILE_DESCRIPTOR = fd; }
newlines, please

2019-02-28 10:39 UTC, emmericp commented on src/memory.h
> +#define HUGE_PAGE_SIZE (1 << HUGE_PAGE_BITS) // 2.097.152 = 2M
use _ or , as separator, please

2019-02-28 10:39 UTC, emmericp commented on README.md
> +The usage of the IOMMU via the `vfio-pci` driver is implemented for ixge devices (Intel X520, X540 and X550).
*ixgbe

oxford comma, please

2019-02-28 10:39 UTC, emmericp commented on README.md
> +	On most Intel machines, the BIOS entry is called `VT-d` and has to be enabled additionally to any other virtualization techniques.
*in addition to (...) technique.

2019-02-28 10:39 UTC, emmericp commented on README.md
> +	Add `intel_iommu=on` to your cmdline (if you are running a grub, the file /etc/default/grub.cfg contains a `GRUB_CMDLINE_LINUX` where you can add it).
path in `backticks`

2019-02-28 10:39 UTC, emmericp commented on src/libixy-vfio.c
> +		error("failed to get VFIO group status. errno: %d", errno);
whole file: printing error numbers without `strerror` is horrible user experience. can this use `check_err` instead?

2019-03-02 13:38 UTC, huberste commented on src/libixy-vfio.c
> +		cfd = open("/dev/vfio/vfio", O_RDWR);
a) it's world-writeable
b) it's already in the README

2019-03-08 13:14 UTC, emmericp commented on src/libixy-vfio.c
> +		check_err((ioctl(cfd, VFIO_CHECK_EXTENSION, VFIO_TYPE1_IOMMU) == 1) - 1, "get Type1 IOMMU support from the IOMMU container");
please don't do that magic -1, that's not very readable

2019-03-08 13:14 UTC, emmericp commented on src/libixy-vfio.c
> +	check_err(((group_status.flags & VFIO_GROUP_FLAGS_VIABLE) > 0) - 1, "get viable VFIO group - are all devices in the group bound to the VFIO driver?");
same

2019-03-27 16:16 UTC, merged